Repository elsa-workflows/elsa-core, pull requests merged in 2021-03, with the labels that each got.

#718 WIP #667 - Webhook activity project
  Elsa.sln
  src/activities/Elsa.Activities.Webhooks/ActivityTypes/WebhookActivityTypeProvider.cs
  src/activities/Elsa.Activities.Webhooks/Elsa.Activities.Webhooks.csproj
  src/activities/Elsa.Activities.Webhooks/Extensions/ElsaOptionsExtensions.cs
  src/activities/Elsa.Activities.Webhooks/FodyWeavers.xml
  src/activities/Elsa.Activities.Webhooks/Models/WebhookDefinition.cs
  src/activities/Elsa.Activities.Webhooks/Options/WebhookOptions.cs
  src/activities/Elsa.Activities.Webhooks/Persistence/Decorators/InitializingStoreBase.cs
  src/activities/Elsa.Activities.Webhooks/Persistence/Decorators/InitializingWebhookDefinitionStore.cs
  src/activities/Elsa.Activities.Webhooks/Persistence/IWebhookDefinitionStore.cs
  src/activities/Elsa.Activities.Webhooks/Persistence/InMemory/InMemoryWebhookStore.cs
  src/activities/Elsa.Activities.Webhooks/Services/IWebhookDefinitionsApi.cs
  src/clients/Elsa.Client/Elsa.Client.csproj
  src/clients/Elsa.Client/ElsaClient.cs
  src/clients/Elsa.Client/IElsaClient.cs
  src/core/Elsa.Abstractions/Metadata/ActivityPropertyDescriptor.cs
  src/core/Elsa.Abstractions/Services/IActivityActivator.cs
  src/dashboards/blazor/ElsaDashboard.Backend/Extensions/ApplicationBuilderExtensions.cs
  src/dashboards/blazor/ElsaDashboard.Backend/Extensions/ServiceCollectionExtensions.cs
  src/dashboards/blazor/ElsaDashboard.Backend/Rpc/WebhookDefinitionService.cs
  src/dashboards/blazor/ElsaDashboard.Shared/Rpc/WebhookDefinition/Models/GetWebhookDefinitionByIdRequest.cs
  src/dashboards/blazor/ElsaDashboard.Shared/Rpc/WebhookDefinition/Services/IWebhookDefinitionService.cs
  src/samples/dashboard/ElsaDashboard.Samples.WebAssembly/ElsaDashboard.Samples.WebAssembly.csproj
  src/server/Elsa.Server.Api/Elsa.Server.Api.csproj
  src/server/Elsa.Server.Api/Endpoints/WebhookDefinitions/Get.cs
  src/server/Elsa.Server.Api/Endpoints/WebhookDefinitions/List.cs
  src/server/Elsa.Server.Api/Swagger/Examples/WebhookDefinitionExample.cs
  src/server/Elsa.Server.Api/Swagger/Examples/WebhookDefinitionListExample.cs
Labels: dashboard, enhancement

#813 Fix build failure: ForEachWorkflowTests
  .gitignore
  src/core/Elsa.Abstractions/Exceptions/CannotSetActivityPropertyValueException.cs
  src/core/Elsa.Abstractions/Services/ActivityPropertyProviders.cs
  src/core/Elsa.Core/Activities/ControlFlow/ForEach/ForEachBuilderExtensions.cs
Labels: bug, prio high

#814 Temporarily disable docker deployment
  appveyor.yml
Labels: bug, prio high

#827 Refactored docker build scripts
  docker/Dockerfile
  docker/ElsaDashboard.Samples.Monolith.Dockerfile
  docker/ElsaDashboard.Samples.Monolith.Dockerfile.Build.cmd
  docker/ElsaDashboard.Samples.Monolith.Dockerfile.Run.cmd
  docker/README.md
  docker/docker-compose.yaml
Labels: devops, enhancement
